In [1]:
import numpy as np

**Basic Operations with 1D and 2D NumPy Array**

In [2]:
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

def basic_numPy_array_operations():
  global arr_1d,arr_2d
  print("1D Array:", arr_1d)
  print("\n2D Array: \n", arr_2d)
  print("\nSum of 1D Array:", np.sum(arr_1d))
  print("\nMean of 2D Array:", np.mean(arr_2d))
  print("\nTranspose of 2D Array:\n", arr_2d.T)

basic_numPy_array_operations()

1D Array: [1 2 3 4 5]

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of 1D Array: 15

Mean of 2D Array: 5.0

Transpose of 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Image Processing with NumPy (Indexing & Slicing in Action) 

In [3]:
def processing_img():
  image = np.random.randint(0, 256, (5, 5), dtype=np.uint8)
  print("Original Image:\n", image)
  cropped = image[1:4, 1:4]
  print("\nCropped Section:\n", cropped)
  inverted_image = 255 - image
  print("\nInverted Image:\n", inverted_image)

processing_img()

Original Image:
 [[188  63 196 145 208]
 [  8 130 109   6 175]
 [ 68 101 109 147 158]
 [139  69  23 143 121]
 [ 17 235   9  65 155]]

Cropped Section:
 [[130 109   6]
 [101 109 147]
 [ 69  23 143]]

Inverted Image:
 [[ 67 192  59 110  47]
 [247 125 146 249  80]
 [187 154 146 108  97]
 [116 186 232 112 134]
 [238  20 246 190 100]]


Augmented Reality Transformation – Perform linear algebra operations like scaling, rotation, and translation.

In [ ]:
import numpy as np
import cv2
image = cv2.imread('b4Jy0kwhnsWcsDQyuzAEsN7RmhQ.jpg') 
def scale_image(image, scale_factor):
    new_width = int(image.shape[1] * scale_factor)
    new_height = int(image.shape[0] * scale_factor)
    scaled_image = cv2.resize(image, (new_width, new_height), interpolation=cv2.INTER_LINEAR)
    return scaled_image
 
def rotate_image(image, angle): 
    rows, cols = image.shape[:2] 
    
    rotation_matrix = cv2.getRotationMatrix2D((cols / 2, rows / 2), angle, 
1) 
     
    rotated_image = cv2.warpAffine(image, rotation_matrix, (cols, rows)) 
    return rotated_image 
 
def translate_image(image, tx, ty):
    translation_matrix = np.array([[1, 0, tx], 
                                   [0, 1, ty]], dtype=np.float32)

    rows, cols = image.shape[:2]

    translated_image = cv2.warpAffine(image, translation_matrix, (cols, rows))
    return translated_image
scaled_image = scale_image(image, 1.5)
rotated_image = rotate_image(image, 45)
translated_image = translate_image(image, 50, 30) 
 
cv2.imshow('Original', image) 
cv2.imshow('Scaled', scaled_image) 
cv2.imshow('Rotated', rotated_image) 
cv2.imshow('Translated', translated_image) 
 
cv2.waitKey(0) 
cv2.destroyAllWindows() 

Face Detection from Image Arrays – Extract facial features by slicing a NumPy-based image array.

In [ ]:
import cv2 
import numpy as np 
 
# Load an image and convert it to a NumPy array 
image = cv2.imread('face.jpg')  # Replace with your image path 
if image is None:
    print("Error: Image not loaded. Check the file path.")
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
 
# Load OpenCV's pre-trained Haar Cascade for face detection 
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 
'haarcascade_frontalface_default.xml') 
 
# Detect faces in the image 
faces = face_cascade.detectMultiScale(image_gray, scaleFactor=1.1, 
minNeighbors=5) 
 
# Loop through the detected faces and extract facial features (regions) 
for (x, y, w, h) in faces:
    # Slice the image array to extract the face region 
    face_region = image[y:y+h, x:x+w] 
     
    # Optional: Display the face region 
    cv2.imshow('Face Region', face_region) 
     
    # Extract additional facial features if required (e.g., eyes, nose) 
    eyes_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 
'haarcascade_eye.xml') 
    eyes = eyes_cascade.detectMultiScale(face_region, scaleFactor=1.1, 
minNeighbors=5) 
     
    for (ex, ey, ew, eh) in eyes: 
        eye_region = face_region[ey:ey+eh, ex:ex+ew] 
        cv2.imshow('Eye Region', eye_region) 
 
# Show the original image with detected faces 
cv2.imshow('Detected Faces', image) 
 
cv2.waitKey(0) 
cv2.destroyAllWindows() 