In [2]:
def multiplier(n):
 def multiply(n):
  return n*n
 return multiply(n);
print(multiplier(5))


25


In [3]:
def fact(n):
  if n==0 or n==1:
    return 1;
  return n*fact(n-1)
print(fact(3))

6


In [7]:
def greet(name):
  """docstring"""
  return name
print(greet("hamdia"))
help(greet)

hamdia
Help on function greet in module __main__:

greet(name)
    docstring



In [9]:
z=5
def modify_global():
  global z
  z=10
modify_global()
print(z)

10


In [11]:
def outer():
  x=10
  def inner():
    nonlocal x
    x=15
  inner()
  print(x)
outer()

15


In [12]:
import numpy as np
lis=['1','2','3']
arr=np.array(lis)
print(type(lis))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [28]:
arr=np.array([['1','2','3'],['1','2','3']])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[['1' '2' '3']
 ['1' '2' '3']]
2
(2, 3)
6


In [16]:
zero_arr=np.zeros((3,4))
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
rand_arr=np.full((3,4),9)
print(rand_arr)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [20]:
lin_arr=np.linspace(3,20,20)#starting,ending,no of values i am interested in
print(lin_arr)
#can control no of output elements i get
#auto decides the gap

[ 3.          3.89473684  4.78947368  5.68421053  6.57894737  7.47368421
  8.36842105  9.26315789 10.15789474 11.05263158 11.94736842 12.84210526
 13.73684211 14.63157895 15.52631579 16.42105263 17.31578947 18.21052632
 19.10526316 20.        ]


In [23]:
range_arr=np.arange(5,30,3)#need to give the gap we want btw values
print(range_arr)

[ 5  8 11 14 17 20 23 26 29]


In [26]:
rand_arr=np.random.rand(2,2)
print(rand_arr)

[[0.2989165  0.99461363]
 [0.86005285 0.76726969]]


In [27]:
rand_arr=np.random.randint(1,5,(3,3))
print(rand_arr)

[[4 2 3]
 [3 4 1]
 [1 4 4]]


In [30]:
arr=np.array([['1','2','3'],['4','5','6'],['7','8','9']])
print(arr[1:2,0:1])


[['4']]


UFuncTypeError: ufunc 'greater' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

In [44]:
arr=np.array([1,2,3,4,5,6,7,8,9])
res=np.where(arr>4)
print(res)
filtered=np.array(np.where(arr>4))
print(filtered)
print(np.take(arr,[2,4,5]))
np.put(arr,[3,4],[100,101])
print(arr)
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))

(array([4, 5, 6, 7, 8]),)
[[4 5 6 7 8]]
[3 5 6]
[  1   2   3 100 101   6   7   8   9]
1
101
237
